#!/bin/sh

mkdir -p ~/projects/prototypes/now-prototype-it-companion &&
rm -Rf ~/projects/prototypes/now-prototype-it-companion/* &&
rm -Rf ~/projects/prototypes/now-prototype-it-companion/.tmp &&
./bin/cli create --version=local ~/projects/prototypes/now-prototype-it-companion
