#!/bin/sh

mkdir -p ~/projects/prototype-kits/now-prototype-it-companion &&
rm -Rf ~/projects/prototype-kits/now-prototype-it-companion/* &&
./bin/cli create --version=local --variant="@nowprototypeit/govuk-frontend-adaptor" --variant-dependency="$(pwd)/../adaptors/govuk-frontend-adaptor" ~/projects/prototype-kits/now-prototype-it-companion
