#!/bin/sh

mkdir -p ~/projects/prototypes/now-prototype-it-companion &&
rm -Rf ~/projects/prototypes/now-prototype-it-companion/* &&
rm -Rf ~/projects/prototypes/now-prototype-it-companion/.tmp &&
./bin/cli create --version=local --variant="marsha-p-johnson" --variant-dependency="$(pwd)/features/fixtures/plugins/marsha-p-johnson" ~/projects/prototypes/now-prototype-it-companion
