#!/bin/sh

mkdir -p ~/projects/prototypes/now-prototype-it-companion &&
rm -Rf ~/projects/prototypes/now-prototype-it-companion/* &&
rm -Rf ~/projects/prototypes/now-prototype-it-companion/.tmp &&
./bin/cli create --version=local --variant="louisa-may-alcott" --variant-dependency="$(pwd)/features/fixtures/plugins/louisa-may-alcott" ~/projects/prototypes/now-prototype-it-companion
