#!/bin/sh

mkdir -p ~/projects/prototype-kits/now-prototype-it-govuk-companion &&
rm -Rf ~/projects/prototype-kits/now-prototype-it-govuk-companion/* &&
./bin/cli create --version=local ~/projects/prototype-kits/now-prototype-it-govuk-companion --use-njk-extensions
