#!/bin/sh

mkdir -p ~/projects/prototype-kits/now-prototype-it-companion &&
rm -Rf ~/projects/prototype-kits/now-prototype-it-companion/* &&
./bin/cli create --version=local ~/projects/prototype-kits/now-prototype-it-companion
