name: Browser Tests

on:
  push:
    branches:
      - main
      - support/*
  pull_request:

jobs:
  tests:

    strategy:
      fail-fast: false  # continue other tests if one test in matrix fails
      matrix:
        node-version: [20.x]
        os: [windows-latest]
        type: [acceptance, integration]

    name: Test ${{ matrix.type }} on Node v${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    steps:
    - run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run test:browser:${{ matrix.type }} -- --retry 2
      env:
        ADDITIONAL_TIMEOUT_MULTIPLIER: 3
        SHOW_KIT_STDIO: 'true'
        VERBOSE: 'true'
