name: Browser Tests

on:
  push:
    branches:
      - main
      - support/*
  pull_request:

jobs:
  tests:

    strategy:
      fail-fast: false  # continue other tests if one test in matrix fails
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [windows-latest, ubuntu-latest, macos-latest]
        type: [acceptance, integration]

    name: Test ${{ matrix.type }} on Node v${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    steps:
    - run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npx playwright install

    - run: npm run test:browser:${{ matrix.type }}
      env:
        ADDITIONAL_TIMEOUT_MULTIPLIER: 3
